<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advertise' => 'Quảng cáo',
    'Body' => 'Nội dung',
    'End At' => 'Kết thúc lúc',
    'ID' => 'ID',
    'Image' => 'Ảnh',
    'Is Show' => 'Hiển thị?',
    'Link' => 'Link',
    'Name' => 'Tên quảng cáo',
    'Position' => 'Vị trí',
    'Start At' => 'Bắt đầu lúc',
    'Type' => 'Loại',
    'Advertises'=> 'Quảng cáo',
    'Create Advertise'=> 'Tạo quảng cáo',
    'Update Advertise: '=> 'Cập nhập quảng cáo',
    'Update'=>'Cập nhập',
    'Create'=>'Tạo',
    'Slide'=>'Slide',
    'Create Slide'=>'Tạo thêm slide',
    'Campain' => 'Chiến dịch',
    'Create Campain'=>'Thêm chiến dịch',
    'All'=>'Xem tất cả',
    'Selecting type...'=>'Lựa chọn loại quảng cáo',
    'Right'=>'Góc trên bên phải',
    'Top'=>'Slide đầu trang',
    'Campain'=>'Chiến dịch cho trung tâm',
    'Selecting position..'=>'Lựa chọn vị trí quảng cáo',
    'Select Photo'=>'Lựa chọn ảnh',
];
