<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Avatar của bạn không hợp lệ' => '',
    'Change' => 'Thay đổi',
    'English' => 'Tiếng Anh',
    'Home' => 'Trang chủ',
    'Login' => 'Đăng nhập',
    'Logout (' => 'Đăng xuất (',
    'My Company' => 'Công ty của tôi',
    'Param' => 'Số lượng hiển thị',
    'Please fill out the following fields to login:' => 'Xin hãy điền thông tin để đang nhập',
    'Vietnamise' => 'Tiếng Việt',
    'Description' => 'Mô tả',
    'ID' => 'ID',
    'Name' => 'Tên',
    'Status' => 'Trạng thái',
    'Value' => 'Giá trị',
    'Params'=>'Hiển thị',
    'Update'=>'Cập nhập',
    'Delete'=>'Xóa',
    'Language\'s Centers'=>'Các trung tâm tiếng Nhật',
    'Create Language\'s Center'=>'Tạo thêm trung tâm',
    'Update Language\'s Center: '=> 'Cập nhập thông tin trung tâm',
    'List user'=>'Danh sách người dùng',
    'Create user'=>'Thêm người dùng',
    'List roles'=>'Danh sách vai trò',
    'Create roles'=>'Thêm vai trò',
    'List permission'=>'Danh sách quyền',
    'Create permission'=>'Thêm quyền',
    'List params'=>'Tùy chọn hiển thị',
    'Homepage'=>'Trang chủ-Quản trị',
    'Welcome'=>'Chào mừng',
    'You signed in us system administrator'=>'Bạn đã đăng nhập hệ thống quả trị của chúng tôi',
    'User'=>'Người dùng',
    'Centers'=>'Trung tâm',
    'Advertise'=>'Quảng cáo',
    'Manage User'=>'Quản lý người dùng',
    'Manage Center'=>'Quản lý trung tâm',
    'Manage Param'=>'Quản lý hiển thị',
    'Manage Advertise'=>'Quản lý quảng cáo'
];
