<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Body' => 'Nội dung',
    'Contact' => 'Liên hệ',
    'Languecenters' => 'Trung tâm ngoại ngữ',
    'My Company' => 'Công ty của tôi',
    'My Computer' => 'Máy tính của tôi',
    'Not rating again!' => 'Không thể đánh giá lại',
    'Popular' => 'Xem nhiều nhất',
    'Rating done!' => 'Đánh giá xong',
    'Reset' => 'Thiết lập lại',
    'Save image' => 'Lưu ảnh',
    'Search' => 'Tìm kiếm',
    'Subject' => 'Chủ đề',
    'Submit' => 'Gửi',
    'Upload image' => 'Tải ảnh',
    'Your email' => 'Email của bạn',
    'Your name' => 'Tên của bạn',
    'Your address'=>'Địa chỉ của trung tâm',
    'Website'=>'Địa chỉ trang web',
    'Your phone'=>'SĐT của trung tâm',
    'Your company'=> 'Tên trung tâm',
    'Homepage'=>'Trang chủ danh sách các trung tâm tiếng nhật',
    'more...'=>'Xem thêm...',
    'Top'=>'Về đầu trang',
    'You rated success {0}. Thank you for your rating!'=> 'Bạn đã đánh giá {0} sao thành công. Cảm ơn đã đánh giá!',
    'You used to rate {0} star. Thank you for your rating!'=>'Bạn đã đánh giá {0} sao rồi. Cám ơn đã đánh giá',
    'Thank you for contacting us. We will respond to you as soon as possible.'=> 'Cảm ơn đã gửi liên hệ cho chúng tôi. Chúng tôi sẽ phản hồi bạn sớm.',
    'There was an error sending email.'=>'Có lỗi trong khi gửi email',
    'Home'=>'Trang chủ',
    'Copyright © 2015 by'=>'Bản quyền © năm 2015 thuộc về ',
    'Contact Center' => 'Liên hệ trung tâm',
    'Contact us' => 'Liên hệ',
    'verifyCode'=>'Mã xác nhận',
    'Get exercise free'=>'Đăng ký nhận bài tập miễn phí',
    'Name'=> 'Tên',
    'Level'=> 'Trình độ',
    'Your level'=>'Trình độ của bạn',
    'Begin study'=>'Bắt đầu học',
    'Sorry!'=> 'Xin lỗi!',
    'You registed email {0}.'=> 'Bạn đã đăng ký email {0} rồi.',
    'Thank your register. The first exercise sent your email!'=> ' Cảm ơn đã đăng ký. Bài tập đầu tiên đã được gửi đến email của bạn',
    'There was an error sending email.'=>'Có lỗi trong quá trình gửi mail',
    'If you want to up your info\'s center, please fill out the following form to contact us. Thank you.'=>'Nếu bạn muốn đưa thông tin của trung tâm bạn lên. Hãy điền vào form và gửi cho chúng tôi. Xin cảm ơn!',
    'Name'=>'Tên',
    'Level'=>'Trình độ',
    'Create'=>'Đăng ký ngày',
    'Delete'=>'Xóa',
    'Are you sure you want to delete this item?'=>'Bạn chắc chắn muốn xóa đối tượng này?'
];
