<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Language Center' => 'Trung tâm Tiếng Nhật',
    'Address' => 'Địa chỉ',
    'Decription' => 'Mô tả',
    'Email' => 'Email',
    'ID' => 'ID',
    'Icon' => 'Ảnh đại diện',
    'Id Center' => 'Id trung tâm',
    'Image' => 'Ảnh',
    'Is Show' => 'Hiển thị?',
    'Name' => 'Tên',
    'Number' => 'Số xem',
    'Ordinal View' => 'Thứ tự hiển thị',
    'Phone' => 'Số điện thoại',
    'Rate' => 'Đánh giá',
    'Rate At' => 'Đánh giá lúc',
    'Schedule' => 'Lịch học',
    'Url' => 'Link web',
    'User Session' => 'Session người dùng',
    'Value' => 'Giá trị',
    'Language \'s Centers'=>'Trung tâm tiếng Nhật',
    'Create Language\'s Center'=>'Tạo thêm trung tâm',
    'Select icon'=>'Chọn ảnh đại diện',
    'Select Photo'=>'Chọn ảnh',
    'Create'=>'Thêm',
    'Update'=>'Cập nhập',
    'Active'=>'Đã đăng ký'
];
