<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth Key' => '',
    'Bio' => '',
    'User' => 'Người dùng',
    'User has been created' => 'Người dùng đã được tạo thành công',
    'User has been updated' => 'Đã cập nhật thông tin thành công',
    'Avatar' => 'Ảnh đại diện',
    'Blocked At' => 'Chặn lúc',
    'Child' => 'Mục con',
    'Confirmed At' => 'Xác nhận lúc',
    'Created At' => 'Tạo lúc',
    'Data' => 'Dữ liệu',
    'Description' => 'Mô tả',
    'Email' => 'Email',
    'Flags' => 'Flags',
    'Gravatar Email' => 'Gravatar Email',
    'Gravatar ID' => 'Gravatar ID',
    'ID' => 'ID',
    'Item Name' => 'Mục tên',
    'Location' => 'Vị trí',
    'Name' => 'Tên',
    'Parent' => 'Mục cha',
    'Password Hash' => 'Mật khẩu mã hóa',
    'Public Email' => 'Email công khai',
    'Registration Ip' => 'Ip đăng ký',
    'Role' => 'Vai trò',
    'Rule Name' => 'Tên vai trò',
    'Type' => 'Loại',
    'Unconfirmed Email' => 'Emai chưa được xác nhận',
    'Updated At' => 'Cập nhật lúc',
    'User ID' => 'ID Người dùng',
    'Username' => 'Tên đang nhập',
    'Website' => 'Trang web',
];
